#------------------------------------------------------------------------------
# Actuator Configuration
#----------------------------------------------------------------------------
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  server:
    port: 9090

grpc:
  port: 50051
  enable-reflection: true
