#------------------------------------------------------------------------------
# gRPC Configuration
#------------------------------------------------------------------------------
grpc:
  host: localhost
  port: 50051

#------------------------------------------------------------------------------
# Server Configuration
#------------------------------------------------------------------------------
server:
  port: 8081
