#------------------------------------------------------------------------------
# gRPC Configuration
#------------------------------------------------------------------------------
grpc:
  host: localhost
  port: 50051
  ca-certificate: ssl/ca.crt

#------------------------------------------------------------------------------
# Server Configuration
#------------------------------------------------------------------------------
server:
  port: 8081
